require:
    - rubocop-rails

AllCops:
    SuggestExtensions: false
    Exclude:
      - 'db/**/*'
      - 'bin/*'
Style/FrozenStringLiteralComment:
    Enabled: false
Metrics/BlockLength:
    Enabled: false
