services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: password
      DATABASE_USERNAME: postgres
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY_BASE: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
