
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', '5') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'counter') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  port: <%= ENV.fetch('DATABASE_PORT', '5432') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>

development:
  <<: *default
  database: counter_app_development

test:
  <<: *default
  database: counter_app_test

production:
  <<: *default
  database: counter_app_production
